### ISSUE TITLE
Password management: salt and others

### ISSUE THREAD

**Issue by radl97** [tatliHU/memewebsite#3]
Salt is usually not global to the database (I've seen a `app.config["salt"]`, but included in each DB entry along with the password hash.

So you should migrate to a DB where each user account has an additional field `salt`, which is a sufficiently long, sufficiently random string.

The main goal of different-salt-for-each-account is that in the event of a DB leak, each user must be cracked separately, and the attacker cannot "take a crack" at everyone's passwords at once, when targeting your DB. For example, if 1000 users have some 10000th most frequent passwords, the attacker does 10000000 hash iterations for cracking it, not 10000.

Also, please use at least SHA256 instead of MD5. They are the same speed, but SHA256 is more secure. (also take a look at bcrypt/scrypt/other password-based key derivation solutions, which would be more preferred solution. Maybe Argon2 is the most loved solution recently)

These changes will be harder after more users are registered (how do you notify them to change their passwords? how do you migrate their accounts?)

The solution of both of these problems can be solved via passlib: Salt+sha256 example usage: https://passlib.readthedocs.io/en/stable/lib/passlib.hash.sha256_crypt.html The passwords are stored along with the SHA hash. This is basically equivalent to how Linux stores passwords.

**Comment by tatliHU** [comment]
Thanks for noticing! I am addressing this issue in a new commit 69e30407467bcbeeef31f516623e2ea966adfb09.
