### ISSUE TITLE
XSS problem

### ISSUE THREAD

**Issue by radl97** [tatliHU/memewebsite#4]
https://github.com/tatliHU/memewebsite/blob/69e30407467bcbeeef31f516623e2ea966adfb09/static/script.js#L26

innerHTML is prone to XSS. There are other suspects too:

https://github.com/tatliHU/memewebsite/blob/69e30407467bcbeeef31f516623e2ea966adfb09/static/script.js#L168

(but I do not know the dataflow, whether the values here are attacker controlled)

To avoid XSS inside the script.js, you should either (i) use templating from Python side, (ii) use safe functions from JS world (which take multiple function calls), or (iii) escape the values (find some code which escapes values from any HTML context (attribute and plain tag context).

To avoid XSS in python (have not found vulnerable stuff), do not generate values inside script tags (e.g. `<script> let val = "{{ somethingservergenerated"; </script>` is bad). (This solution frequently comes up when you try to implement rigid CSRF protection for a `fetch()`, so be aware)

**Comment by tatliHU** [comment]
Good call.
https://github.com/tatliHU/memewebsite/blob/69e30407467bcbeeef31f516623e2ea966adfb09/static/script.js#L26
is an attack surface because some user input variables are not properly sanitized for HTML/CSS/JS code.

**Comment by radl97** [comment]
to be fair, I would suggest just hitting up Copilot to generate this structure without using innerHTML. This is a tad safer, because you do not have to escape stuff.

I think Copilot would output code a bit like "create a node, create first child node, set it up, connect it to main node, etc.".

Now the reason why you would not need to escape this, is that there is no setting innerHTML (you could use ".textContent").

**Comment by tatliHU** [comment]
Resolved in 1a204cb9fa2be1d95b37f63d9776940030ef673d. Thank you for the help.
